name: CI - Test, Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/salary-predictor:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/salary-predictor:latest

    - name: SSH and deploy (inline script)
      run: |
        gcloud compute ssh chandradeepbandari48@l00187658-dockernode \
          --zone=europe-west4-b \
          --command="
              cd /home/chandradeepbandari48/ && \
              rm -rf final-project && \
              git clone https://github.com/chandradeep-bandari/final-project.git && \
              cd final-project && \
              /usr/local/bin/minikube kubectl -- delete -f k8s-deployment.yaml || true && \
              sleep 5 && \
              /usr/local/bin/minikube kubectl -- apply -f k8s-deployment.yaml"
